/**
 * coronavirus-server
 * coronavirus-server
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

import { GetMinVersion } from '../model/getMinVersion';
import { UpdateMinVersion } from '../model/updateMinVersion';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';



@Injectable({
  providedIn: 'root'
})
export class MinVersionControllerService {

    protected basePath = 'http://localhost:3000';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }



    /**
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public minVersionControllerFind(observe?: 'body', reportProgress?: boolean): Observable<GetMinVersion>;
    public minVersionControllerFind(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GetMinVersion>>;
    public minVersionControllerFind(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GetMinVersion>>;
    public minVersionControllerFind(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.get<GetMinVersion>(`${this.configuration.basePath}/min-version`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param updateMinVersion 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public minVersionControllerReplaceById(updateMinVersion?: UpdateMinVersion, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public minVersionControllerReplaceById(updateMinVersion?: UpdateMinVersion, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public minVersionControllerReplaceById(updateMinVersion?: UpdateMinVersion, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public minVersionControllerReplaceById(updateMinVersion?: UpdateMinVersion, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<any>(`${this.configuration.basePath}/min-version`,
            updateMinVersion,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param frontVersion 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public minVersionControllerUpdateNeeded(frontVersion: string, observe?: 'body', reportProgress?: boolean): Observable<boolean>;
    public minVersionControllerUpdateNeeded(frontVersion: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<boolean>>;
    public minVersionControllerUpdateNeeded(frontVersion: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<boolean>>;
    public minVersionControllerUpdateNeeded(frontVersion: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (frontVersion === null || frontVersion === undefined) {
            throw new Error('Required parameter frontVersion was null or undefined when calling minVersionControllerUpdateNeeded.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.get<boolean>(`${this.configuration.basePath}/min-version/${encodeURIComponent(String(frontVersion))}/update_needed`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
